### PR TITLE
Port to 3.0.0

### PR DESCRIPTION
**Pull request by KingOfTurkey38**
Title is self explanatory.

Code i used to test whether it works or not: [https://gist.github.com/KingOfTurkey38/16c85674a763efe848b4a6453f770232]()

### CODE REVIEW

**Comment by Frago9876543210** [comment]
I can merge it into 3.0 branch only and fetch commits from your repository.

**Comment by KingOfTurkey38** [comment]
Wdym? Do you want me to change the branch name to 3.0?

**Comment by Frago9876543210** [comment]
I don't plan to support 3.0. It would be dropped soon.

**Comment by KingOfTurkey38** [comment]
Welp okay then you can close this PR if you don't want 3.0 support

**Comment by Frago9876543210** [comment]
Merged as https://github.com/Frago9876543210/EasyForms/tree/3.0.0

**Pull request closed without merging**
